export { default as NavBar } from './navbar/Navbar'
export { default as DropDown } from './navbar/DropDown'
export { default as Header } from './homepage/Header'
export { default as About } from './homepage/About'
export { default as OurGames } from './homepage/OurGames'
export { default as JoinTeam } from './homepage/JoinTeam'