export { default as Home } from './Home'
export { default as Games } from './Games'
export { default as About } from './About'
export { default as Careers } from './Careers'
export { default as Position } from './Position'
export { default as PolicyAndTerms } from './PolicyAndTerms'
export { default as NotFound } from './NotFound'