export { default as Navbar } from './navbar'
export { default as Logo } from './logo'
export { default as Dropdown } from './dropdown'
export { default as HeaderHome } from './home_header'
export { default as About } from './home_about'
export { default as OurGames } from './home_our-games'
export { default as JoinTeam } from './home_join-team'
export { default as HeaderCareers } from './careers_header'
export { default as JobsPosition } from './careers_jobs-position'
export { default as HeaderAbout } from './about_header'
export { default as Info } from './about_info'
export { default as Founder } from './about_founder'
export { default as Offices } from './about_offices'
export { default as HeaderGames } from './games_header'
export { default as Screenshots } from './games_screenshots'
export { default as Reviews } from './games_reviews'
export { default as HeaderPosition } from './position_header'
export { default as ContentPosition } from './position_content'
export { default as Gallery } from './gallery'
export { default as Content } from './policy&terms'
export { default as Footer } from './footer'
export { default as PositionForm } from './form/PositionForm'

export { FormContainer, SubscribeForm } from './form/Form'
export { NotFoundPage, Container } from './not-found/NotFoundStyled'
export { Button, ButtonLink, ButtonScrollToTop } from './button'