export { default as Navbar } from './navbar'
export { default as Logo } from './logo'
export { default as Dropdown } from './dropdown'
export { default as HeaderHome } from './header_home'
export { default as About } from './about_home'
export { default as OurGames } from './our-games_home'
export { default as JoinTeam } from './join-team_home'
export { default as HeaderCareers } from './header_careers'
export { default as JobsPosition } from './jobs-position_careers'
export { default as HeaderAbout } from './header_about'
export { default as Info } from './info_about'
export { default as Founder } from './founder_about'
export { default as Offices } from './offices_about'
export { default as HeaderGames } from './header_games'
export { default as Screenshots } from './screenshots_games'
export { default as Reviews } from './reviews_games'
export { default as HeaderPosition } from './header_position'
export { default as ContentPosition } from './content_position'
export { default as Gallery } from './gallery'
export { default as Content } from './policy&terms'
export { default as Footer } from './footer'
export { default as ScrollToTop } from './scrollTo/ScrollToTop'
export { default as PositionForm } from './form/PositionForm'

export { FormContainer, SubscribeForm } from './form/Form'
export { NotFoundPage, Container } from './not-found/NotFoundStyled'
export { Button, ButtonLink } from './button'